### ISSUE TITLE
Minor: Template-Python.ipynb

### ISSUE THREAD

**Issue by warmlogic** [jbwhit/svds-style#3]
Small suggestions for the `Template-Python.ipynb` notebook, in the "Presentation Template" cell.

Clarification: "Use markdown cells to begin each section with a heading, and subsections with subheadings, using # and ## and ### in descending hierarchy."

The word "be" is missing from the following sentence: "The template is not intended to *be* an overly rigid document."

**Comment by jbwhit** [comment]
Fixed!
